-- ==============================================================================
-- 1. WATCHLIST ENTRIES TABLE
-- ==============================================================================

CREATE TABLE public.watchlist_entries (
    -- Primary key is highly recommended even with the unique constraint below
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- Supabase standard for linking to authenticated users
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    
    mal_id INTEGER NOT NULL,
    title TEXT NOT NULL,
    
    -- Enforce the specific allowed status strings
    status TEXT NOT NULL CHECK (status IN ('watching', 'completed', 'on_hold', 'dropped', 'plan_to_watch')),
    
    -- Enforce the 0-10 scoring rule
    score INTEGER CHECK (score >= 0 AND score <= 10),
    
    watched_episodes INTEGER DEFAULT 0,
    total_episodes INTEGER,
    poster_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Prevent users from adding the same anime to their list twice
    UNIQUE(user_id, mal_id)
);

-- Enable RLS
ALTER TABLE public.watchlist_entries ENABLE ROW LEVEL SECURITY;

-- Create policies (ALL permits SELECT, INSERT, UPDATE, and DELETE for the user)
CREATE POLICY "Users can fully manage their own watchlist entries"
    ON public.watchlist_entries 
    FOR ALL 
    USING (auth.uid() = user_id) 
    WITH CHECK (auth.uid() = user_id);


-- ==============================================================================
-- 2. ANIME METADATA TABLE (Jikan Cache)
-- ==============================================================================

CREATE TABLE public.anime_metadata (
    mal_id INTEGER PRIMARY KEY,
    genres TEXT[] DEFAULT '{}',
    type TEXT,
    studio TEXT,
    year INTEGER,
    synopsis TEXT,
    cached_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- While not strictly requested to hide this, it's good practice to enable RLS 
-- and make cached metadata explicitly readable by everyone.
ALTER TABLE public.anime_metadata ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anime metadata is readable by everyone"
    ON public.anime_metadata 
    FOR SELECT 
    USING (true);


-- ==============================================================================
-- 3. PUSH SUBSCRIPTIONS TABLE
-- ==============================================================================

CREATE TABLE public.push_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    endpoint TEXT NOT NULL UNIQUE,
    p256dh TEXT NOT NULL,
    auth_key TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Create policies so users can manage their own notification subscriptions
CREATE POLICY "Users can fully manage their own push subscriptions"
    ON public.push_subscriptions 
    FOR ALL 
    USING (auth.uid() = user_id) 
    WITH CHECK (auth.uid() = user_id);